package la.devpicon.android.grenzezwielicht.utils

//constants used for locations samples

const val CUSTOM_INTENT_USER_ACTION = "USER-ACTIVITY-DETECTION-INTENT-ACTION"
const val CUSTOM_REQUEST_CODE_USER_ACTION = 1000

const val CUSTOM_INTENT_GEOFENCE = "GEOFENCE-TRANSITION-INTENT-ACTION"
const val CUSTOM_REQUEST_CODE_GEOFENCE = 1001

const val FINE_LOCATION_ACCESS_REQUEST_CODE = 1024
const val BACKGROUND_LOCATION_ACCESS_REQUEST_CODE = 1025